### ISSUE TITLE
Problem with sharp corner

### ISSUE THREAD

**Issue by hankstag** [huxingyi/isotropicremesher#3]
Hello, thank you for sharing this, it's been very helpful!
I encountered some cases where the remesher produces some artifects:
input:
<img src="https://user-images.githubusercontent.com/6883726/206345284-99db5a25-c9ac-464b-b90b-b8e964786788.png" width="400">
output:
<img src="https://user-images.githubusercontent.com/6883726/206345450-fbd2a014-900f-4e75-bf4e-9ad049608357.png" width="400">
The options I used: 
```
isotropicRemesher.setTargetTriangleCount(53);
isotropicRemesher.remesh(5);
```
here are the input & output data:
[remesher_data.zip](https://github.com/huxingyi/isotropicremesher/files/10181743/remesher_data.zip)
In general I would like to ask is it always gurateneed the old boundary vertices will be preserved? Thank you!

**Comment by huxingyi** [comment]
Hi, thanks, the boundary vertices should be preserved now in https://github.com/huxingyi/isotropicremesher/commit/d4674ce63288d7a55a70735181049895aebc3bf7

**Comment by hankstag** [comment]
Thank you! This solved my problem!
